alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
alias cwd="pwd | xclip -sel clip"
alias cd..="cd .."
alias mkdir="mkdir -pv"
alias histg="history | grep"
alias top="htop"
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias h="history"
alias ports="netstat -tulanp"
alias wget="wget -c "
